### ISSUE TITLE
Some bugs in COMPARE_SELF

### ISSUE THREAD

**Issue by timukasr** [SlexAxton/gaga.js#3]
Found 2 bugs in COMPARE_SELF object.
1. When comparing two cards, it uses card values, which are actually strings. This works for numbers, but not for T, J, Q, K, A, which are compared alphabetically.  Same bug in UTIL.reverseCompare.
2. There should be `return UTIL.reverseCompare(h1.cards, h2.cards);` at the end of "two_pair" function (in case both players have same two pair).

**Comment by SlexAxton** [comment]
I updated stuff and I still pass the tests I wrote before (which apparently aren't good enough, but not nothing...).

Let me know if that fixes things for you. Thanks!

**Comment by timukasr** [comment]
Full House comparison still uses string values.
2. bug (comparing hands with same two pair) still exists. For example, this gives `undefined`:
    console.log(
        gaga.compareHands(
          gaga.createHand([
            [4, 'c'],
            [2, 'd'],
            [2, 'h'],
            ['A', 's'],
            ['A', 's']
          ]),
          gaga.createHand([
            [3, 'h'],
            [2, 'd'],
            [2, 's'],
            ['A', 'c'],
            ['A', 's']
          ]) 
        )
    );

Also, hand comparison test seems a bit confusing (maybe that's just me). It tests whether h2 is weaker and at first glance it seems that test should fail because K from h2 is stronger than any number from h1. Only later I realized that there's 1 (Ace) in h1.

**Comment by SlexAxton** [comment]
Check out the latest updates and let me know if that helps things. Thanks again for going through everything.

**Comment by timukasr** [comment]
Still some bugs:

In full house comparison function, you have lines like `h1c_3 = UTIL.getCardOrderIndex( val );`, where `val` is value of a card (K for example), but UTIL.getCardOrderIndex requires Card object for first argument. Using `UTIL.getCardOrderIndex( cards[0] );` will fix it.

In two pair comparison function, you are using identified hands for reverseCompare. Identified hands include only four cards (from the two pairs) and since execution got this far, they're equal. At this point, it should compare the fifth card or just use reverseCompare with whole hand (h1.cards and h2.cards)
